//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvivorLeague.NFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueSeason
    {
        public int LeagueId { get; set; }
        public int SeasonId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int StartWeek { get; set; }
    }
}
